## 🪄 Based on https://github.com/TurboLabIt/symfony-bundle-builder/blob/main/template/config/services.yaml
#
# 📚 Usage example (customize with your own):
#
# - MyVendorName   ➡ TurboLabIt
# - MyPackageName  ➡ BaseCommand
#
# 💡 "Replace all" the above and you're ready to go
#
# 📚 Resources:
#
# - https://symfony.com/doc/current/bundles.html
# - https://symfonycasts.com/screencast/symfony-bundle/bundle-directory

services:
    MyVendorName\MyPackageNameBundle\Service\MyService:
      autowire: true
      public: true
